spring:
  application:
    name: placesee-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    url: /v3/api-docs

server:
  servlet:
    context-path: /
  port: ${PORT:8081}

storage:
  upload-dir: ./images

gis:
  maps:
    base-url: "https://routing.api.2gis.com/routing"
    api-key: ${TWO_GIS_API_KEY}

supabase:
  base-url: "https://lqtiftmgexxmtoohvldc.supabase.co"
  api-key: ${SUPABASE_API_KEY}
  bucket-name: "place_photos"