spring:
  application:
    name: fgislk-pul-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/photo_routes
    username: photo_user
    password: photo_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /
  port: 8081